---
# dev_reg.yml
# Satellite 6.14 -> 6.17 Host Re-Registration Orchestration
# Designed for AAP execution with Machine Credential attached
#
# AAP Requirements:
#   - Satellite API Credential (provides app_username/app_password)
#   - Machine Credential (provides ansible_user/ansible_password/ansible_ssh_private_key_file)
#   - Survey input: satellite_org

- name: "Export and Prepare Host Data"
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - "{{ playbook_dir }}/group_vars/dev.yml"
  collections:
    - redhat.satellite
    - theforeman.foreman
    - community.general
  pre_tasks:
    - name: Validate required survey variables are provided
      ansible.builtin.assert:
        that:
          - satellite_org is defined
          - satellite_org | length > 0
          - app_username is defined
          - app_password is defined
        fail_msg: "Required variables missing. Verify AAP survey inputs and credentials are attached to job template."
        success_msg: "All required variables validated successfully."
  roles:
    - export_hosts
    - prepare_import
    - provision_lifecycle_env
    - generate_registration_command

- name: "Re-Register Hosts to Satellite 6.17"
  hosts: satellite_migration_hosts
  become: true
  gather_facts: false
  serial: "{{ batch_size | default(50) }}"
  collections:
    - redhat.satellite
    - theforeman.foreman
    - community.general
  roles:
    - register_hosts

- name: "Validate and Log Results"
  hosts: satellite_migration_hosts
  gather_facts: false
  collections:
    - redhat.satellite
    - theforeman.foreman
    - community.general
  roles:
    - validate

- name: "Generate Final Summary"
  hosts: localhost
  gather_facts: false
  roles:
    - log_results